openapi: 3.0.3
info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Proof Pass API
  version: 0.1.0
servers:
- description: Localhost development server
  url: http://localhost:3000/v1
- description: Production server
  url: https://api.proofpass.io/v1
paths:
  /health:
    get:
      responses:
        "200":
          description: The API is healthy
      summary: Check the health of the API
  /events:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Event'
                type: array
          description: List of events
      summary: Get list of events
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: Event created successfully
      security:
      - bearerAuth: []
      summary: Create a new event
  /events/{eventId}:
    get:
      parameters:
      - explode: false
        in: path
        name: eventId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: Event details
      summary: Get event details
    put:
      parameters:
      - explode: false
        in: path
        name: eventId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: Event updated successfully
      security:
      - bearerAuth: []
      summary: Update an event
  /events/{eventId}/request-ticket-credential:
    post:
      parameters:
      - explode: false
        in: path
        name: eventId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnencryptedTicketCredential'
          description: Ticket credential generated successfully
      security:
      - bearerAuth: []
      summary: Request a new ticket credential for an event
  /events/{eventId}/attendance:
    post:
      parameters:
      - explode: false
        in: path
        name: eventId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordAttendanceRequest'
        required: true
      responses:
        "201":
          description: Attendance recorded successfully
      summary: Record attendance for an event
  /user/request-verification-code:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEmailVerificationRequest'
        required: true
      responses:
        "200":
          description: Verification code sent successfully
      summary: Request an email verification code
  /user/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: Login successful
      summary: User login
  /user/me:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User details retrieved successfully
      security:
      - bearerAuth: []
      summary: Get user details
  /user/update:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User details updated successfully
      security:
      - bearerAuth: []
      summary: Update user details
  /user/me/email-credential:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailCredential'
          description: User email credential retrieved successfully
      security:
      - bearerAuth: []
      summary: Get user email credential
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutEmailCredentialRequest'
        required: true
      responses:
        "201":
          description: Email credential stored successfully
      security:
      - bearerAuth: []
      summary: Store user email credential with encrypted data
  /user/me/ticket-credentials:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TicketCredential'
                type: array
          description: User credentials retrieved successfully
      security:
      - bearerAuth: []
      summary: Get user ticket credentials
  /user/me/ticket-credential:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutTicketCredentialRequest'
        required: true
      responses:
        "201":
          description: Ticket credential stored successfully
      security:
      - bearerAuth: []
      summary: Store user ticket credential with encrypted data
  /user/me/request-email-credential:
    post:
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnencryptedEmailCredential'
          description: Email credential generated successfully
      security:
      - bearerAuth: []
      summary: Generate a new email credential
components:
  schemas:
    Event:
      example:
        end_date: 2000-01-23T04:56:07.000+00:00
        chain_id: chain_id
        context_string: context_string
        name: name
        description: description
        context_id: context_id
        issuer_key_id: issuer_key_id
        id: id
        url: url
        start_date: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        chain_id:
          type: string
        context_id:
          type: string
        context_string:
          type: string
        issuer_key_id:
          type: string
        start_date:
          format: date-time
          type: string
        end_date:
          format: date-time
          type: string
      type: object
    RecordAttendanceRequest:
      example:
        admin_code: admin_code
        event_id: event_id
        key_id: key_id
        nullifier: nullifier
        context: context
        type: type
      properties:
        type:
          type: string
        context:
          type: string
        nullifier:
          type: string
        key_id:
          type: string
        event_id:
          type: string
        admin_code:
          type: string
      type: object
    UserEmailVerificationRequest:
      example:
        email: email
      properties:
        email:
          type: string
      type: object
    UserLogin:
      example:
        code: code
        email: email
      properties:
        email:
          type: string
        code:
          type: string
      type: object
    LoginResponse:
      example:
        token: token
      properties:
        token:
          type: string
      type: object
    User:
      example:
        encrypted_internal_nullifier: encrypted_internal_nullifier
        identity_commitment: identity_commitment
        is_encrypted: true
        encrypted_identity_secret: encrypted_identity_secret
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        email: email
      properties:
        id:
          type: string
        email:
          type: string
        identity_commitment:
          type: string
        encrypted_internal_nullifier:
          type: string
        encrypted_identity_secret:
          type: string
        is_encrypted:
          type: boolean
        created_at:
          format: date-time
          type: string
      type: object
    UserUpdate:
      example:
        encrypted_internal_nullifier: encrypted_internal_nullifier
        identity_commitment: identity_commitment
        encrypted_identity_secret: encrypted_identity_secret
      properties:
        identity_commitment:
          type: string
        encrypted_internal_nullifier:
          type: string
        encrypted_identity_secret:
          type: string
      type: object
    EmailCredential:
      example:
        identity_commitment: identity_commitment
        data: data
        expire_at: 2000-01-23T04:56:07.000+00:00
        id: id
        issued_at: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          type: string
        identity_commitment:
          type: string
        data:
          type: string
        issued_at:
          format: date-time
          type: string
        expire_at:
          format: date-time
          type: string
      type: object
    PutEmailCredentialRequest:
      example:
        data: data
        expire_at: 2000-01-23T04:56:07.000+00:00
        issued_at: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          type: string
        issued_at:
          format: date-time
          type: string
        expire_at:
          format: date-time
          type: string
      type: object
    UnencryptedEmailCredential:
      example:
        credential: credential
        expire_at: 2000-01-23T04:56:07.000+00:00
        issued_at: 2000-01-23T04:56:07.000+00:00
      properties:
        credential:
          type: string
        issued_at:
          format: date-time
          type: string
        expire_at:
          format: date-time
          type: string
      type: object
    TicketCredential:
      example:
        event_id: event_id
        data: data
        expire_at: 2000-01-23T04:56:07.000+00:00
        id: id
        issued_at: 2000-01-23T04:56:07.000+00:00
        email: email
      properties:
        id:
          type: string
        email:
          type: string
        event_id:
          type: string
        data:
          type: string
        issued_at:
          format: date-time
          type: string
        expire_at:
          format: date-time
          type: string
      type: object
    PutTicketCredentialRequest:
      example:
        event_id: event_id
        data: data
        expire_at: 2000-01-23T04:56:07.000+00:00
        issued_at: 2000-01-23T04:56:07.000+00:00
      properties:
        event_id:
          type: string
        data:
          type: string
        issued_at:
          format: date-time
          type: string
        expire_at:
          format: date-time
          type: string
      type: object
    UnencryptedTicketCredential:
      example:
        event_id: event_id
        credential: credential
        expire_at: 2000-01-23T04:56:07.000+00:00
        issued_at: 2000-01-23T04:56:07.000+00:00
      properties:
        event_id:
          type: string
        credential:
          type: string
        issued_at:
          format: date-time
          type: string
        expire_at:
          format: date-time
          type: string
      type: object
    CreateEventRequest:
      example:
        end_date: 2000-01-23T04:56:07.000+00:00
        admin_code: admin_code
        name: name
        description: description
        url: url
        start_date: 2000-01-23T04:56:07.000+00:00
      properties:
        name:
          type: string
        description:
          type: string
        url:
          type: string
        admin_code:
          type: string
        start_date:
          format: date-time
          type: string
        end_date:
          format: date-time
          type: string
      type: object
    UpdateEventRequest:
      example:
        end_date: 2000-01-23T04:56:07.000+00:00
        admin_code: admin_code
        name: name
        description: description
        url: url
        start_date: 2000-01-23T04:56:07.000+00:00
      properties:
        name:
          type: string
        description:
          type: string
        url:
          type: string
        admin_code:
          type: string
        start_date:
          format: date-time
          type: string
        end_date:
          format: date-time
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
